
export const GET_BASEBUSINESSTYPES_ACTION = 'get_baseBusinessTypes_action'
export const GET_BASEBUSINESSTYPESLIST_ACTION = 'get_baseBusinessTypesList_action'
export const GET_BASECURSTOMERS_ACTION = 'get_basecustomers_action'
export const GET_BASECURSTOMERSLIST_ACTION = 'get_basecustomerslist_action'
export const GET_BASESERVICES_ACTION = 'get_baseservices_action'
export const GET_BASESERVICESLIST_ACTION = 'get_baseserviceslist_action'
export const CHANGE_BASECURSTOMERSLIST_ACTION = 'change_basecustomerslist_action'
export const GET_SUPPLIER_ACTION = 'change_supplier_action'
export const GET_SUPPLIERLIST_ACTION = 'change_supplierList_action'
export const CHANGE_DATERANGE_ACTION = 'change_dateRange_action'
export const DOWNFILE_ACTION = 'downFile_action'
export const GET_PARAMSBYSERVICENAME_ACTION = 'getParamsByServiceName_action'
export const GET_PARAMSBYSERVICENAMELIST_ACTION = 'getSeviceNamePramasList_action'
export const GET_GUID_ACTION = 'get_guid_action'
export const GET_GUIDRESULT_ACTION = 'get_guidResult_action'
export const GET_VERIFYCODE_ACTION = 'get_VerifyCode_action'
export const GET_VERIFYCODEIMAGE_ACTION = 'get_VerifyCodeImage_action'
export const DO_LOGIN_ACTION = 'do_login_action'
export const CONFIRM_LANDING_ACTION = 'confirm_landing_action'

