
export const GET_LIGHTSIGNIN_CUSTOMERS_ACTION = 'get_lightSignIn_customers_action'
export const GET_LIGHTSIGNIN_CUSTOMERS_LIST_ACTION = 'get_lightSignIn_customers_list_action'
export const GET_LIGHTSIGNIN_APPINFO_ACTION = 'get_lightSignIn_appInfo_action'
export const GET_LIGHTSIGNIN_APPINFO_LIST_ACTION = 'get_lightSignIn_appInfo_list_action'
export const GET_APPINFODETAIL_ACTION = 'get_appInfoDetail_action'
export const GET_APPINFODETAILNEWS_ACTION = 'get_appInfoDetailNews_action'